[package]
name = "in-summer-we-render"
version = "0.1.0"
authors = ["weitsang <weitsang@nus.edu.sg>", "hungkhoaitay <e0550385@u.nus.edu>", "giterator <e0552200@u.nus.edu>"]
edition = "2018"

description = "This project aims to design and develop a set of robust and high performance Unix CLI tools for analyzing, processing, debugging, and viewing 3D point clouds using Rust"
readme = "README.md"
repository = "https://github.com/hungkhoaitay/in-summer-we-render"

license = "Apache-2.0"
keywords = ["3D", "ISWR"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true

[features]
#default = ["by_radius", "dim_6"] #by_knn #by_radius #dim_3 #dim_6
by_radius = []
by_knn = []
dim_3 = []
dim_6 = []

[lib]
name = "iswr"
path = "src/lib.rs"

[dependencies]
ply-rs = { git = "https://github.com/hungkhoaitay/ply-rs", version = "0.1.3" }
kiss3d = { git = "https://github.com/nus-mmsys/kiss3d", version = "0.31.0", features = [ "conrod" ] } #"0.31.0"
nalgebra = "0.26.2"
# kiddo =  {git = "https://github.com/giterator/kiddo"}  #"0.1.4" 
kiddo = "0.2.3"
typenum = "1.13.0"
rand = "0.8.3"
lab = "0.10.0"
clap = "2.33.3"
error-chain = "0.12.4"
image = "0.23"
approx = { version = "0.5", default-features = false }
clipboard = "0.5.0"

[[bin]]
name = "ply_to_ply"

[[bin]]
name = "ply_view"

[[bin]]
name = "ply_to_png"

[[bin]]
name = "ply_interpolate"

[[bin]]
name = "ply_fat"

[[bin]]
name = "test"
