[package]
name = "vivotk"
version = "0.1.0"
authors = ["weitsang <weitsang@nus.edu.sg>", "hungkhoaitay <e0550385@u.nus.edu>", "giterator <e0552200@u.nus.edu>"]
edition = "2021"

description = "This project aims to design and develop a set of robust and high performance Unix CLI tools for analyzing, processing, debugging, and viewing 3D point clouds using Rust"
readme = "README.md"
repository = "https://github.com/nus-mmsys/vivotk"

license = "Apache-2.0"
keywords = ["3D", "Point Cloud", "Volumetric Video"]
categories = ["command-line-utilities"]
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true

[lib]
name = "vivotk"
path = "src/lib.rs"

[dependencies]
ply-rs = { git = "https://github.com/hungkhoaitay/ply-rs", version = "0.1.3" }
clap = { version = "3.0.14", features = ["derive"] }
image = "0.24.3"
clipboard = "0.5.0"
thiserror = "1.0"
byteorder = "1.4.3"
bytemuck = { version = "1.7.3", features = [ "derive" ] }
cgmath = "0.18.0"
pollster = "0.2.5"
rayon = "1.5.1"
kdam = "0.2"
reqwest = { version = "0.11", features = ["blocking", "gzip"], default-features = false }
anyhow = "1.0"
tempfile="3"
roxmltree = "0.15"
kiddo = "0.2.4"
winit = { version = "0.27.3", optional = true }
wgpu = { version = "0.13.1", optional = true }
wgpu_glyph = { version = "0.17.0", optional = true }
egui = { version = "0.19.0", optional = true }
egui_winit_platform = { version = "0.16.0", optional = true } 
egui_wgpu_backend = { version = "0.19.0", optional = true }
epi = { version = "0.17.0", optional = true }
regex = "1.6.0"

[[bin]]
name = "ply_play"

[[bin]]
name = "vvdash"

[[bin]]
name = "vivotk"

[features]
default = ["render"]
render = ["dep:winit", "dep:wgpu", "dep:wgpu_glyph", "dep:egui", "dep:egui_winit_platform", "dep:egui_wgpu_backend", "dep:epi"]